### ISSUE TITLE
ToDo Stuff

### ISSUE THREAD

**Issue by JadeOfMaar** [Galileo88/JNSQ#1]
As @Sigma88 did before this repo was wiped :stuck_out_tongue: I'm making a to-do here. Suggestions, requests and discussion welcome.

## Will happen
* [ ] Add sea/ocean biomes to Kerbin, Laythe
* [ ] New ground scatters and anomalies
  * [ ] Science for these
* [ ] Update biome maps for:
  * [ ] Edna
  * [ ] Tylo
  * [ ] Riga
* [x] Localization

## Might happen
* [ ] Wiki (needs @OhioBob )
* [ ] Flags for new planets
  * [ ] New flags for stock planets

**Comment by gordonfpanam** [comment]
How about a localization dictionary file? I see many of the displayNames are plain en-us text. Do we want a community-created dictionary for every item, or use the stock ones where applicable, or neither?

If this gets attempted, remember to store the dictionary as UTF-8 text. KSP seems to use that formatting to support non-ANSI characters. Also, I know a thing or two about KSP localization and can set up a separate repository for others to contribute to.

**Comment by JadeOfMaar** [comment]
@gordonfpanam Currently we're not interested in localizing JNSQ. Setting this up is a large task on its own and something that should be left until all variables that can be localized are set in stone (namely, the many biome maps and any unique biomes. These are still wide open for change and would be quite displeasing to have to revisit in steps).

**Comment by woeller** [comment]
Now that it has happened, how about those loading tips? They would be easy to translate.

**Comment by JadeOfMaar** [comment]
You can start but I don't think it is supported. The loading tips are stored in a text file, not a config file, so they can't be formatted for localization. That might change soon enough. It's a tiny mod and Sigma is a seasoned coder.
Until it's supported, we could attach a separate download for German users to grab and it will overwrite the default tips file.

**Comment by Sigma88** [comment]
Actually I think it might be possible with some minor changes to the code

**Comment by Sigma88** [comment]
case in point

<img src="https://cdn.discordapp.com/attachments/377968025506414593/672903180169904142/unknown.png" width="50%" />

**Comment by JadeOfMaar** [comment]
@woeller @gordonfpanam Localization (even to the loading tips) is now available. Have at it, guys. :)
